baseurl: "https://0101sec.com"
languageCode: "zh-cn"
title: "rhmaskçš„åšå®¢"
theme: "hugo-tania"
paginate: 6


params:
  titleEmoji: ğŸ§‘â€ğŸ’»
  enableFootnotes: true
  # siteName: "rhmaskçš„åšå®¢"
  siteDesc: "å­¦ä¹ /å·¥ä½œ/æ—¥å¸¸è¸©å‘è®°å½•"
  author: "rhmask"
  colorScheme:
    toggle: true
    default: auto

  maxCategoryToShow: 10
  socialOptions:
    email: rhmask@163.com
    github: https://github.com/rhmask

menu:
  header:
    - name: Articles
      url: "/articles/"
      weight: 1
    - name: Tags
      url: "/tags/"
      weight: 2
    - name: About
      url: "/about/"
      weight: 3
   
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]